# Generated by Django 3.2.8 on 2021-11-27 04:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_users_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
