# Generated by Django 3.2.8 on 2021-11-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20211127_1039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
