# Generated by Django 3.2.8 on 2021-11-28 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Category'},
        ),
    ]
