# Generated by Django 3.2.8 on 2021-11-28 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_categories_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Categories', 'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Items', 'verbose_name_plural': 'Item'},
        ),
        migrations.AlterModelOptions(
            name='purchases',
            options={'verbose_name': 'Purchases', 'verbose_name_plural': 'Purchase'},
        ),
    ]
